In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
dataset = pd.read_csv('C:/Users/Win10/Desktop/tyl/emails.csv')

In [114]:
X = dataset.iloc[:, [100,3000]].values
y = dataset.iloc[:, -1].values

In [115]:
X

array([[0, 0],
       [0, 0],
       [0, 0],
       ...,
       [0, 0],
       [0, 0],
       [0, 0]], dtype=int64)

In [116]:
y

array([0, 0, 0, ..., 1, 1, 0], dtype=int64)

In [117]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 0)

In [118]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [119]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [120]:
y_pred = classifier.predict(X_test)
y_pred

array([1, 0, 0, ..., 0, 1, 0], dtype=int64)

In [121]:
from sklearn.metrics import confusion_matrix, accuracy_score
ac = accuracy_score(y_test,y_pred)
cm = confusion_matrix(y_test, y_pred)

In [122]:
ac

0.7690821256038647

In [77]:
cm

array([[711,  39],
       [271,  14]], dtype=int64)

In [124]:
from sklearn.model_selection import train_test_split

In [133]:
X = dataset.drop(['Prediction','Email No.'], axis='columns')
y = dataset.Prediction

In [134]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [135]:
len(X_train)

4137

In [136]:
len(X_test)

1035

In [137]:
from sklearn.svm import SVC
model = SVC()

In [138]:
model.fit(X_train, y_train)

SVC()

In [139]:
model.score(X_test, y_test)

0.8009661835748793